# Generated by Django 4.1 on 2022-09-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.CharField(default='github.com/your-github-profile', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(default='Your Job Title', max_length=30),
        ),
    ]
